### ISSUE TITLE
Error running test-integration

### ISSUE THREAD

**Issue by xtagon** [screepers/screeps-typescript-starter#112]
Hi,

I'm setting up screeps-typescript-starter on Windows, followed the tutorial, and unit tests run fine but I can't seem to get the integration tests working.

Relevant environment:

- Windows 10 (Build 18362)
- Node 10.16.3
- Python 2.7.16
- Visual Studio 2019 Community Edition
- Git Bash for Windows (where I run the npm scripts, inside VS Code)

Here's the error I get:

```
$ npm run test-integration

> screeps-typescript-starter@3.0.0 test-integration C:\Users\xtago\Alpha\Projects\Selpla\selpla
> npm run build && rollup -c rollup.test-integration-config.js && mocha dist/test-integration.bundle.js


> screeps-typescript-starter@3.0.0 build C:\Users\xtago\Alpha\Projects\Selpla\selpla
> rollup -c

No destination specified - code will be compiled but not uploaded
cleared:  C:\Users\xtago\Alpha\Projects\Selpla\selpla\dist

src/main.ts → dist/main.js...
created dist/main.js in 1.2s

test/integration/**/*.test.ts → dist/test-integration.bundle.js...
(!) `this` has been rewritten to `undefined`
https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined
test\integration\helper.ts
1: var _this = this;
               ^
2: import * as tslib_1 from "tslib";
3: var readFileSync = require('fs').readFileSync;
created dist/test-integration.bundle.js in 1.2s


  main
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! screeps-typescript-starter@3.0.0 test-integration: `npm run build && rollup -c rollup.test-integration-config.js && mocha dist/test-integration.bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the screeps-typescript-starter@3.0.0 test-integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xtago\AppData\Roaming\npm-cache\_logs\2019-10-16T03_47_52_118Z-debug.log
```

And here's the full debug log:

```
info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\xtago\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test-integration' ]
2 info using npm@6.12.0
3 info using node@v10.16.3
4 verbose run-script [ 'pretest-integration',
4 verbose run-script   'test-integration',
4 verbose run-script   'posttest-integration' ]
5 info lifecycle screeps-typescript-starter@3.0.0~pretest-integration: screeps-typescript-starter@3.0.0
6 info lifecycle screeps-typescript-starter@3.0.0~test-integration: screeps-typescript-starter@3.0.0
7 verbose lifecycle screeps-typescript-starter@3.0.0~test-integration: unsafe-perm in lifecycle true
8 verbose lifecycle screeps-typescript-starter@3.0.0~test-integration: PATH: C:\Users\xtago\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\xtago\Alpha\Projects\Selpla\selpla\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\xtago\bin;C:\Python27;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\NVIDIA Corporation\NVIDIA NGX;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files\dotnet;C:\Users\xtago\AppData\Local\Microsoft\WindowsApps;C:\Users\xtago\AppData\Roaming\npm
9 verbose lifecycle screeps-typescript-starter@3.0.0~test-integration: CWD: C:\Users\xtago\Alpha\Projects\Selpla\selpla
10 silly lifecycle screeps-typescript-starter@3.0.0~test-integration: Args: [ '/d /s /c',
10 silly lifecycle   'npm run build && rollup -c rollup.test-integration-config.js && mocha dist/test-integration.bundle.js' ]
11 silly lifecycle screeps-typescript-starter@3.0.0~test-integration: Returned: code: 1  signal: null
12 info lifecycle screeps-typescript-starter@3.0.0~test-integration: Failed to exec test-integration script
13 verbose stack Error: screeps-typescript-starter@3.0.0 test-integration: `npm run build && rollup -c rollup.test-integration-config.js && mocha dist/test-integration.bundle.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\xtago\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\xtago\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid screeps-typescript-starter@3.0.0
15 verbose cwd C:\Users\xtago\Alpha\Projects\Selpla\selpla
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xtago\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test-integration"
18 verbose node v10.16.3
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error screeps-typescript-starter@3.0.0 test-integration: `npm run build && rollup -c rollup.test-integration-config.js && mocha dist/test-integration.bundle.js`
22 error Exit status 1
23 error Failed at the screeps-typescript-starter@3.0.0 test-integration script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

From what I can tell, it failed to spawn a process, but I am not sure why exactly? Any help is appreciated!

**Comment by brisberg** [comment]
This was a known failure at the time of the integration testing. The integration testing dependency has since been removed to simplify the set up of a "starter". However, if you update your version of `screeps-server-mockup` to 1.5 it should be fixed. But no guarantee.

Sorry for the late necro lol

**Comment by xtagon** [comment]
Thank you!

Updating to 1.5 fixes this error, but causes a new error: https://github.com/screepers/screeps-server-mockup/issues/22
